# Generated by Django 5.0.7 on 2024-08-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0007_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='exit', max_length=15),
            preserve_default=False,
        ),
    ]
