# Generated by Django 5.0.7 on 2024-08-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0009_alter_order_name_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': ('Catagories',)},
        ),
        migrations.AlterModelTable(
            name='catagory',
            table='Catagory',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
